sudo: required
dist: trusty

language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"


services: docker

env:
  matrix:
  - INSTANCE=ubuntu:14.04
  - INSTANCE=ubuntu:16.04
  - INSTANCE=ubuntu:18.04
  #- INSTANCE=ubuntu:15.04
  #- INSTANCE=ubuntu:17.04
  #- INSTANCE=debian:jessie
  #- INSTANCE=debian:wheezy

script: ./build.sh
